
const PHOENIX1_UNIT_TYPE = FourCC( "h00F" );
const PHOENIX2_UNIT_TYPE = FourCC( "h00G" );
const PHOENIX3_UNIT_TYPE = FourCC( "h00H" );
export const PHOENIX_UNIT_TYPES = [ PHOENIX1_UNIT_TYPE, PHOENIX2_UNIT_TYPE, PHOENIX3_UNIT_TYPE ];
