// AUTO-GENERATED by scripts/generateQuickShop.ts — do not edit.
// Sourced from QUICK_SHOP_PAGE_SHOPS' Items Sold (`usei`) field at build time.
export const quickShopPages: string[][] = [
  [
    "fgrg", // qsA0
    "fgfh", // qsA1
    "tfar", // qsA2
    "pspd", // qsA3
    "pman", // qsA4
    "pinv", // qsA5
    "pnvu", // qsA6
    "I003", // qsA7
    "I004", // qsA8
    "gobm", // qsA9
  ],
  [
    "arsh", // qsB0
    "hlst", // qsB1
    "tkno", // qsB2
    "mcou", // qsB3
    "bspd", // qsB4
    "clsd", // qsB5
    "I005", // qsB6
    "gemt", // qsB7
    "I001", // qsB8
    "tels", // qsB9
  ],
  [
    "rat9", // qsC0
    "rat6", // qsC1
    "ratc", // qsC2
    "ratf", // qsC3
    "I002", // qsC4
    "I000", // qsC5
    "ofir", // qsC6
    "clfm", // qsC7
    "gcel", // qsC8
  ],
];
