name: test

on:
  push:
    paths:
      - '**.ts'
      - 'package.json'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Runs tests
      run: |
        npm i
        npm test
